# Generated by Django 4.0.2 on 2022-02-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.IntegerField()),
                ('sepal_width', models.IntegerField()),
                ('petal_length', models.IntegerField()),
                ('petal_width', models.IntegerField()),
            ],
        ),
    ]
